import { SpecialProvisionsMap } from "../lookupFunctions/specialProvisions";

/* these are workflow modifiers that need further planning */
export const numericSpecialProvisionsModifiers: SpecialProvisionsMap = {
  "134":
    "This entry only applies to vehicles powered by wet batteries, sodium batteries, lithium metal batteries or lithium-ion batteries and equipment powered by wet batteries or sodium batteries that are transported with these batteries installed.\na. For the purpose of this special provision, vehicles are self-propelled apparatus designed to carry one or more persons or goods. Examples of such vehicles are electrically-powered cars, motorcycles, scooters, three- and four-wheeled vehicles or motorcycles, trucks, locomotives, bicycles (pedal cycles with an electric motor) and other vehicles of this type (e.g., self-balancing vehicles or vehicles not equipped with at least one seating position), lawn tractors, self-propelled farming and construction equipment, boats, aircraft, wheelchairs and other mobility aids. This includes vehicles transported in a packaging. In this case some parts of the vehicle may be detached from its frame to fit into the packaging. b. Examples of equipment are lawnmowers, cleaning machines or model boats and model aircraft. Equipment powered by lithium metal batteries or lithium ion batteries must be consigned under the entries “Lithium metal batteries contained in equipment” or “Lithium metal batteries packed with equipment” or “Lithium ion batteries contained in equipment” or “Lithium-ion batteries packed with equipment” as appropriate. (T-0).\nc. Self-propelled vehicles or equipment that also contain an internal combustion engine must be consigned under the entries “Engine, internal combustion, flammable gas powered” or “Engine, internal combustion, flammable liquid powered” or “Vehicle, flammable gas powered” or “Vehicle, flammable liquid powered,” as appropriate. (T-0). These entries include hybrid electric vehicles powered by both an internal combustion engine and batteries. Additionally, self-propelled vehicles or equipment that contain a fuel cell engine must be consigned under the entries “Engine, fuel cell, flammable gas powered” or “Engine, fuel cell, flammable liquid powered” or “Vehicle, fuel cell, flammable gas powered” or “Vehicle, fuel cell, flammable liquid powered,” as appropriate. (T-0). These entries include hybrid electric vehicles powered by a fuel cell engine, an internal combustion engine, and batteries. powered” or “Vehicle, fuel cell, flammable liquid powered,” as appropriate.",
  "135":
    "Internal combustion engines installed in a vehicle must be consigned under the entries “Vehicle, flammable gas powered” or “Vehicle, flammable liquid powered,” as appropriate. (T-0). If a vehicle is powered by a flammable liquid and a flammable gas internal combustion engine, it must be consigned under the entry “Vehicle, flammable gas powered.” (T-0). These entries include hybrid electric vehicles powered by both an internal combustion engine and wet, sodium or lithium batteries installed. If a fuel cell engine is installed in a vehicle, the vehicle must be consigned using the entries “Vehicle, fuel cell, flammable gas powered” or “Vehicle, fuel cell, flammable liquid powered,” as appropriate. (T-0). These entries include hybrid electric vehicles powered by a fuel cell, an internal combustion engine, and wet, sodium or lithium batteries installed. For the purpose of this special provision, vehicles are self-propelled apparatus designed to carry one or more persons or goods. Examples of such vehicles are cars, motorcycles, trucks, locomotives, scooters, three- and four-wheeled vehicles or motorcycles, lawn tractors, self-propelled farming and construction equipment, boats and aircraft.",
  "362":
    "This entry applies to liquids, pastes or powders, pressurized with a propellant that meets the definition of a gas in 49 CFR Section 173.115. A chemical under pressure packaged in an aerosol dispenser must be transported under UN1950. (T-0). The chemical under pressure must be classed based on the hazard characteristics of the components in the propellant; the liquid; or the solid. (T-0). The following provisions also apply:\n(1) If one of the components, which can be a pure substance or a mixture, is classed as flammable, the chemical under pressure must be classed as flammable in Division 2.1. (T-0). Flammable components are flammable liquids and liquid mixtures, flammable solids and solid mixtures or flammable gases and gas mixtures meeting the following criteria:\n(a) A flammable liquid is a liquid having a flash point of not more than 93 °C (200 °F); (b) A flammable solid is a solid that meets the criteria in 49 CFR Section 173.124; or (c) A flammable gas is a gas that meets the criteria in 49 CFR Section 173.115.\n(2) Gases of Division 2.3 and gases with a subsidiary hazard of 5.1 must not be used as a propellant in a chemical under pressure. (T-0).\n(3) Where the liquid or solid components are classed as Division 6.1, packing groups II or III, or Class 8, packing groups II or III, the chemical under pressure must be assigned a subsidiary hazard of Division 6.1 or Class 8 and the appropriate identification number must be assigned. (T-0). Components classed as Division 6.1, packing group I, or Class 8, packing group I, must not be offered for transportation and transported under this description. (T-0).\n(4) A chemical under pressure with components meeting the properties of : Class 1 (explosives); Class 3 (liquid desensitized explosives); Division 4.1 (self-reactive substances and solid desensitized explosives); Division 4.2 (substances liable to spontaneous combustion); Division 4.3 (substances which, in contact with water, emit flammable gases or toxic gases); Division 5.1 (oxidizing substances); Division 5.2 (organic peroxides); Division 6.2 (Infectious substances); or, Class 7 (Radioactive material), must not be offered for transportation under this description. (T-0).\n(5) A description to which Special provision 170 or TP7 is assigned in Column 7 of the 172.101 Hazardous Materials Table, and therefore requires air to be eliminated from the package vapor space by nitrogen or other means, must not be offered for transportation under this description. (T-0).",
  "388":
    "Lithium batteries containing both primary lithium metal cells and rechargeable lithium ion cells that are not designed to be externally charged, must meet the following conditions: i. The rechargeable lithium-ion cells can only be charged from the primary lithium metal cells;\nii. Overcharge of the rechargeable lithium-ion cells is precluded by design;\niii. The battery has been tested as a primary lithium battery; and\niv. Component cells of the battery must be of a type proved to meet the respective testing requirements of the Manual of Tests and Criteria, part III, subsection 38.3.\nThese lithium batteries must be assigned to UN3090 or UN3091, as appropriate. When such batteries are transported in accordance with 49 CFR Paragraph 173.185(c), the total lithium content of all lithium metal cells contained in the battery must not exceed 1.5 g and the total capacity of all lithium ion cells contained in the battery must not exceed 10 Wh. (T-0).",
  "391":
    "Articles containing hazardous materials of Division 2.3, Division 4.2, Division 4.3, Division 5.1, Division 5.2, or Division 6.1 (substances with a inhalation toxicity of Packing Group I) and articles containing more than one of the following hazards: (1) Gases of Class 2; (2) Liquid desensitized explosives of Class 3; or (3) Self-reactive substances and solid desensitized explosives of Division 4.1, may only be offered for transportation and transported under conditions approved by the DOT Associate Administrator.",
};
