import { SpecialProvisionsMap } from "../../../lookupFunctions/specialProvisions";

export const numericSpecialProvisionsModifiers: SpecialProvisionsMap = {
  "1": "This material is poisonous by inhalation in Hazard Zone A, describe as an inhalation hazard.",
  "2": "This material is poisonous by inhalation in Hazard Zone B, describe as an inhalation hazard.",
  "3": "This material is poisonous by inhalation in Hazard Zone C, describe as an inhalation hazard.",
  "4": "This material is poisonous by inhalation in Hazard Zone D, describe as an inhalation hazard.",
  "6": "This material is poisonous by inhalation and must be described as an inhalation hazard. (T-0).",
  "8": "A hazardous substance that is not a hazardous waste may be shipped under the shipping description “Other regulated substance, liquid or solid”, as appropriate.",
  "13": "Enter the words “Inhalation Hazard” on each shipping paper in association with the shipping description.",
  "30": "Sulphur is not regulated if transported in a non-bulk packaging or if formed to a specific shape (e.g., prills, granules, pellets, pastilles, or flakes).",
  "33": "Ammonium nitrites and mixtures of an inorganic nitrite with an ammonium salt are prohibited.",
  // "39": "This substance may be carried under provisions other than those of Class 1 only if it is so packed that the percentage of water will not fall below that stated at any time during transport. When phlegmatized with water and inorganic inert material, the content of urea nitrate must not exceed 75 percent by mass and the mixture should not be capable of being detonated by test 1(a)(i) or test 1(a)(ii) in the UN Manual of Tests and Criteria.",
  "46": "During transport, it must be protected from direct sunshine and stored (or kept) in a cool and well-ventilated place, away from all sources of heat. (T-0).",
  "51": "This description applies to items previously described as “Toy propellant devices, Class C” and includes reloaded kits. Model rocket motors containing 30 grams or less propellant are classed as Division 1.4S and items containing more than 30 grams of propellant but not more than 62.5 grams of propellant are classed as Division 1.4C.",
  "53": 'Packages of these materials must bear a subsidiary hazard label, "EXPLOSIVE", unless exempted by the DOT. (T-0). A copy of the permit must accompany the shipment. (T-0).',
  "111":
    "Explosive substances of Class 1.1A are forbidden for transportation if dry or not desensitized, unless incorporated in a device.",
  "134":
    "This entry only applies to vehicles powered by wet batteries, sodium batteries, lithium metal batteries or lithium-ion batteries and equipment powered by wet batteries or sodium batteries that are transported with these batteries installed.\na. For the purpose of this special provision, vehicles are self-propelled apparatus designed to carry one or more persons or goods. Examples of such vehicles are electrically-powered cars, motorcycles, scooters, three- and four-wheeled vehicles or motorcycles, trucks, locomotives, bicycles (pedal cycles with an electric motor) and other vehicles of this type (e.g., self-balancing vehicles or vehicles not equipped with at least one seating position), lawn tractors, self-propelled farming and construction equipment, boats, aircraft, wheelchairs and other mobility aids. This includes vehicles transported in a packaging. In this case some parts of the vehicle may be detached from its frame to fit into the packaging. b. Examples of equipment are lawnmowers, cleaning machines or model boats and model aircraft. Equipment powered by lithium metal batteries or lithium ion batteries must be consigned under the entries “Lithium metal batteries contained in equipment” or “Lithium metal batteries packed with equipment” or “Lithium ion batteries contained in equipment” or “Lithium-ion batteries packed with equipment” as appropriate. (T-0).\nc. Self-propelled vehicles or equipment that also contain an internal combustion engine must be consigned under the entries “Engine, internal combustion, flammable gas powered” or “Engine, internal combustion, flammable liquid powered” or “Vehicle, flammable gas powered” or “Vehicle, flammable liquid powered,” as appropriate. (T-0). These entries include hybrid electric vehicles powered by both an internal combustion engine and batteries. Additionally, self-propelled vehicles or equipment that contain a fuel cell engine must be consigned under the entries “Engine, fuel cell, flammable gas powered” or “Engine, fuel cell, flammable liquid powered” or “Vehicle, fuel cell, flammable gas powered” or “Vehicle, fuel cell, flammable liquid powered,” as appropriate. (T-0). These entries include hybrid electric vehicles powered by a fuel cell engine, an internal combustion engine, and batteries. powered” or “Vehicle, fuel cell, flammable liquid powered,” as appropriate.",
  "135":
    "Internal combustion engines installed in a vehicle must be consigned under the entries “Vehicle, flammable gas powered” or “Vehicle, flammable liquid powered,” as appropriate. (T-0). If a vehicle is powered by a flammable liquid and a flammable gas internal combustion engine, it must be consigned under the entry “Vehicle, flammable gas powered.” (T-0). These entries include hybrid electric vehicles powered by both an internal combustion engine and wet, sodium or lithium batteries installed. If a fuel cell engine is installed in a vehicle, the vehicle must be consigned using the entries “Vehicle, fuel cell, flammable gas powered” or “Vehicle, fuel cell, flammable liquid powered,” as appropriate. (T-0). These entries include hybrid electric vehicles powered by a fuel cell, an internal combustion engine, and wet, sodium or lithium batteries installed. For the purpose of this special provision, vehicles are self-propelled apparatus designed to carry one or more persons or goods. Examples of such vehicles are cars, motorcycles, trucks, locomotives, scooters, three- and four-wheeled vehicles or motorcycles, lawn tractors, self-propelled farming and construction equipment, boats and aircraft.",
  "165":
    "These substances are susceptible to exothermic decomposition at elevated temperatures. Decomposition can be initiated by heat, moisture or by impurities (e.g., powdered metals (iron, manganese, cobalt, magnesium)). During the course of transportation, these substances must be shaded from direct sunlight and all sources of heat and be placed in adequately ventilated areas. (T-0).",
  "177":
    "Gasoline, or, ethanol and gasoline mixtures, for use in internal combustion engines (e.g., in automobiles, stationary engines and other engines) must be assigned to Packing Group II regardless of variations in volatility. (T-0).",
  "182":
    "Equipment containing only lithium batteries must be classified as either UN3091 or UN3481. (T- 0).",
  "328":
    "When lithium metal or lithium ion batteries are contained in the fuel cell system, the item must be described under this entry and the appropriate entries for “Lithium metal batteries contained in equipment” or “Lithium ion batteries contained in equipment”. (T-0).",
  "332":
    "“Magnesium nitrate hexahydrate” is not subject to the requirements of this manual.",
  "346":
    "“Nitrogen, refrigerated liquid (cryogenic liquid), UN1977” transported in accordance with the requirements for open cryogenic receptacles in 49 CFR Section 173.320 and this special provision are not subject to any other requirements of this manual. The receptacle must contain no hazardous materials other than the liquid nitrogen which must be fully absorbed in a porous material in the receptacle. (T-0).",
  "349":
    "Mixtures of hypochlorite with an ammonium salt are forbidden for transport. A hypochlorite solution, UN1791, is a Class 8 corrosive material.",
  "361":
    "Capacitors with an energy storage capacity of 0.3 Wh or less are not subject to the requirements of this manual. Energy storage capacity means the energy held by a capacitor, as calculated using the nominal voltage and capacitance. This entry does not apply to capacitors that by design maintain a terminal voltage (e.g., asymmetrical capacitors.)",
  "362":
    "This entry applies to liquids, pastes or powders, pressurized with a propellant that meets the definition of a gas in 49 CFR Section 173.115. A chemical under pressure packaged in an aerosol dispenser must be transported under UN1950. (T-0). The chemical under pressure must be classed based on the hazard characteristics of the components in the propellant; the liquid; or the solid. (T-0). The following provisions also apply:\n(1) If one of the components, which can be a pure substance or a mixture, is classed as flammable, the chemical under pressure must be classed as flammable in Division 2.1. (T-0). Flammable components are flammable liquids and liquid mixtures, flammable solids and solid mixtures or flammable gases and gas mixtures meeting the following criteria:\n(a) A flammable liquid is a liquid having a flash point of not more than 93 °C (200 °F); (b) A flammable solid is a solid that meets the criteria in 49 CFR Section 173.124; or (c) A flammable gas is a gas that meets the criteria in 49 CFR Section 173.115.\n(2) Gases of Division 2.3 and gases with a subsidiary hazard of 5.1 must not be used as a propellant in a chemical under pressure. (T-0).\n(3) Where the liquid or solid components are classed as Division 6.1, packing groups II or III, or Class 8, packing groups II or III, the chemical under pressure must be assigned a subsidiary hazard of Division 6.1 or Class 8 and the appropriate identification number must be assigned. (T-0). Components classed as Division 6.1, packing group I, or Class 8, packing group I, must not be offered for transportation and transported under this description. (T-0).\n(4) A chemical under pressure with components meeting the properties of : Class 1 (explosives); Class 3 (liquid desensitized explosives); Division 4.1 (self-reactive substances and solid desensitized explosives); Division 4.2 (substances liable to spontaneous combustion); Division 4.3 (substances which, in contact with water, emit flammable gases or toxic gases); Division 5.1 (oxidizing substances); Division 5.2 (organic peroxides); Division 6.2 (Infectious substances); or, Class 7 (Radioactive material), must not be offered for transportation under this description. (T-0).\n(5) A description to which Special provision 170 or TP7 is assigned in Column 7 of the 172.101 Hazardous Materials Table, and therefore requires air to be eliminated from the package vapor space by nitrogen or other means, must not be offered for transportation under this description. (T-0).",
  "368":
    "In the case of non-fissile or fissile-excepted uranium hexafluoride, the material must be classified under UN3507 or UN2978. (T-0).",
  "369":
    "This radioactive material in an excepted package possessing toxic and corrosive properties is classified in Division 6.1 with radioactivity and corrosive subsidiary risks.",
  "388":
    "Lithium batteries containing both primary lithium metal cells and rechargeable lithium ion cells that are not designed to be externally charged, must meet the following conditions: i. The rechargeable lithium-ion cells can only be charged from the primary lithium metal cells;\nii. Overcharge of the rechargeable lithium-ion cells is precluded by design;\niii. The battery has been tested as a primary lithium battery; and\niv. Component cells of the battery must be of a type proved to meet the respective testing requirements of the Manual of Tests and Criteria, part III, subsection 38.3.\nThese lithium batteries must be assigned to UN3090 or UN3091, as appropriate. When such batteries are transported in accordance with 49 CFR Paragraph 173.185(c), the total lithium content of all lithium metal cells contained in the battery must not exceed 1.5 g and the total capacity of all lithium ion cells contained in the battery must not exceed 10 Wh. (T-0).",
  "391":
    "Articles containing hazardous materials of Division 2.3, Division 4.2, Division 4.3, Division 5.1, Division 5.2, or Division 6.1 (substances with a inhalation toxicity of Packing Group I) and articles containing more than one of the following hazards: (1) Gases of Class 2; (2) Liquid desensitized explosives of Class 3; or (3) Self-reactive substances and solid desensitized explosives of Division 4.1, may only be offered for transportation and transported under conditions approved by the DOT Associate Administrator.",
};

export const pCodeModifiers: SpecialProvisionsMap = {
  /* applicable across all hazardous materials, all materials must have a P code no matter what */
  P1: "Transport this material on dedicated airlift (e.g., Special Assignment Airlift Mission) aircraft as identified in Attachment 24. Material authorized on cargo aircraft only. Passenger deviations are not authorized.",
  P2: "Transport this material on cargo aircraft only. Passenger deviations are not authorized.",
  P3: "Transport this material on cargo aircraft only. Deviations are authorized according to paragraph 2.2. and Attachment 22.",
  P4: "Transport this material on cargo aircraft only. Deviations are authorized according to paragraph 2.2. and Attachment 22. DOD duty passengers do not require a deviation.",
  P5: "Transport this material on passenger or cargo aircraft without passenger restriction.",
};

export const aCodeSpecialProvisionsModifiers: SpecialProvisionsMap = {
  A1: "Single packaging is not permitted on aircraft carrying passengers. P4 restrictions apply.",
  A2: "Single packagings are not permitted.",
  A3: "For combination packagings, if glass inner packagings (including ampoules) are used, they must be packed with absorbent material in tightly closed rigid and leak proof receptacles before packing in outer packaging's. (T-0).",
  A4: "Liquids having an inhalation toxicity of packingGroup I and are identified as P1, P2, or P3 are not permitted on passenger aircraft. Deviations are not allowed.",
  A5: "Solids having an inhalation toxicity of packingGroup I and are identified as P1, P2, or P3, are not permitted on passenger aircraft and may not exceed a maximum net quantity per package of 15 kg (33 pounds) on cargo aircraft. See paragraph 2.2. for deviation authority.",
  A19: "Combination packaging's consisting of outer fiber drums or plywood drums, with inner plastic packaging's, are not authorized.",
  A20: "Plastic bags as inner receptacles of combination packaging's are not authorized.",
  A29: "Combination packaging's consisting of outer expanded plastic boxes with inner plastic bags are not authorized.",
  A30: "Ammonium permanganate is not authorized.",
  A35: "This includes material which is not covered by any other hazard class but has anesthetic, narcotic, noxious or other properties such that, in the event of spillage or leakage on the aircraft, extreme annoyance or discomfort could be caused to aircrew members so as to prevent correct performance of assigned duties. For material containing aromatic extract or flavoring, use packaging paragraph A13.2. For all other material shipped under this PSN, use packaging paragraph A13.14.",
  A43: "Toxins from plant, animal or bacterial sources, which contain infectious substances, or toxins that are contained in infectious substances, must be classified as Division 6.2. (T-0).",
  A56: "Radioactive material with a subsidiary hazard of Division 4.2 Packing Group I must be transported in Type B packages when offered for transportation by aircraft. Radioactive material with a subsidiary hazard of Division 2.1 is forbidden from transport on passenger aircraft.",
  A58: "An aqueous solution containing 24% or less alcohol by volume and more than 50% water is not subject to these regulations.",
  A61: "When used for purposes such as sterilization, inner packaging's of peroxyacetic acid, stabilized, classified as UN3107 Organic peroxide type E, liquid or UN3109 Organic peroxide type F, liquid may be fitted with a vent consisting of hydrophobic membrane, provided:\n(1) Each inner packaging contains not more than 70 mL;\n(2) The inner packaging is designed so that the vent is not immersed in liquid in any orientation;\n(3) Each inner packaging is enclosed in an intermediate rigid plastic packaging with a small opening to permit release of gas and contains a buffer that neutralizes the contents of the inner packaging in the event of leakage;\n(4) Intermediate packaging's are packed in a fiberboard box (4G) outer packaging;\n(5) Each outer packaging contains not more than 1.4 L of liquid; and\n(6) The rate of oxygen release from the outer packaging does not exceed 15 mL per hour.\nSuch packages must be transported on cargo aircraft only. (T-0).",
  A67: "Non-spillable batteries are considered dry batteries and not subject to any other requirements of this manual if:\n(1) At a temperature of 55 degrees C (130 degrees F), the electrolyte will not flow from a ruptured or cracked case and there is no free liquid to flow; (T-0).\n(2) Securely packed in strong outer packaging's or secured to skids or pallets capable of withstanding the shocks normally incident to transportation. The batteries must be loaded or braced so as to prevent damage and short circuits in transit, and any other material loaded in the same vehicle must be blocked, braced, or otherwise secured to prevent contact with or damage to the batteries. (T-0). A non-spillable battery which is an integral part of and necessary for the operation of mechanical or electronic equipment must be securely fastened in the battery holder on the equipment. (T-0).",
  A69: "May be transported using a DOT hazard classification approval. Except for Class/Division 1.4S, a copy of the approval must accompany the shipment. (T-0). See A3.3.1.4.",
  A124: "Only mixtures with not more than 23.5% oxygen may be transported under this entry. A Division 5.1 subsidiary hazard label is not required for any concentration within this limit.",
  A140: "Technical name must not be shown on the package, but must be shown on the shipper’s declaration for dangerous goods. (T-0). When the infectious substances to be transported are unknown, but suspected of meeting the criteria for inclusion in Category A and assigned to UN2814 or UN2900, the words “Suspected Category A Infectious Substance” must be shown in parenthesis following the proper shipping name on the shipper’s declaration for dangerous goods but not on the outer package. (T-0).",
  A191: "Notwithstanding the Division 6.1 subsidiary hazard for this description, the toxic subsidiary hazard label and the requirement to indicate the subsidiary hazard on the shipping paper are not required for manufactured articles containing less than 5 kg (11 pounds) of mercury.",
  A197: "Marine Pollutants in single or combination packagings containing a net quantity per single or inner packaging of 5 L or less for liquids or having a net mass of 5 kg or less for solids, are not subject to any other requirements of this mnanual provided the packagings meet the general requirements in Attachment 3. This exception does not apply to marine pollutants that are a hazardous waste or a hazardous substance. In the case of marine pollutants also meeting the criteria for inclusion in another hazard class, all provisions of this manual relevant to any additional hazards continue to apply.",
  A213: "Lithium batteries containing both primary lithium metal cells and rechargeable lithium ion cells must be assigned to UN numbers 3090 or 3091 as appropriate. (T-0).",
  A500: "P2 Code applies if rocket motor contains hypergolic liquids.",
  A502: "With approval of Shipper's HAZMAT service focal point (see paragraph 1.2.2.), may be shipped as P2.",
  A503: "Only Class 2 (non-toxic aerosols only), Class 3 (Packing Group II or III only) and Division 6.1 (Packing Group III only) provided such substances do not have a subsidiary hazard may be shipped to an international (non-domestic) location as a Class 9.",
  A507: "Determine passenger eligibility (“P” Coded special provisions) for radioactive materials as follows: (1) Radioactive materials requiring a Category III-Yellow label are transported under the provisions of P3. Deviations not authorized unless radioactive material intended for use in, or incident to, research, medical diagnosis, or treatment. Also see A22.1.7.2.\n(2) Radioactive materials requiring a Category II-Yellow label are transported under the provisions of P4. Deviations not authorized unless radioactive material intended for use in, or incident to, research, medical diagnosis, or treatment, and the total TI of all of the packages is 50 TI or less. Also see A22.1.7.2. (3) Radioactive materials requiring a Category I-White or no label are transported under the provisions of P5. Also see A3.3.7.5.4.",
  A508: "Diagnostic, Patient, or Clinical Specimens not containing a Category A or B infectious substances are not regulated by this manual.",
  A509: "Magnesium alloys with 50% or less magnesium in pellets, turning or ribbons are not regulated.",
};

export const nCodeSpecialProvisionsModifiers: SpecialProvisionsMap = {
  N3: "Glass inner packagings are permitted in combination or composite packagings only if the hazardous material is free from hydrofluoric acid.",
  N4: "For combination or composite packagings, glass inner packagings, other than ampoules, are not permitted.",
  N5: "Glass materials of construction are not authorized for any part of the packaging which is normally in contact with the hazardous material.",
  // N8: "Nitroglycerin solution in alcohol may be transported under this entry only when the solution is packed in metal cans of not more than 1 L capacity each, overpacked in a wooden box containing not more than 5 L. Completely surround metal cans with absorbent material. Completely line wooden boxes with a suitable material impervious to water and nitroglycerin.",
  N12: "Plastic packagings are not authorized.",
  N25: "Steel single packagings are not authorized.",
  N32: "Aluminum materials of construction are not authorized for single packagings.",
  N33: "Aluminum drums are not authorized.",
  N34: "Aluminum construction materials are not authorized for any part of a packaging which is normally in contact with the hazardous materials.",
  N36: "Aluminum or aluminum alloy construction materials are permitted only for halogenated hydrocarbons that will not react with aluminum.",
  N37: "This material may be shipped in an integrally-lined fiber drum (1G) which meets the general packaging requirements of Attachment 3, the UN performance tests required based on the packingGroup assigned to the material and to any other special provisions of column 7 of Table A4.1.",
  N40: "This material is not authorized in the following packaging's:\n(1) A combination packaging consisting of a 4G fiberboard box with inner receptacles of glass or earthenware.\n(2) A single packaging of a 4C2 sift-proof, natural wood box.\n(3) A composite packaging 6packingGroup2 (glass, porcelain, or stoneware receptacles within a fiberboard box).",
  N41: "Metal construction materials are not authorized for any part of a packaging that is normally in contact with the hazardous material.",
  // N42: "1A1 drums made of carbon steel with thickness of body and heads of not less than 1.3 mm (0.050 inch) and with a corrosion-resistant phenolic lining are authorized for stabilized benzyl chloride if tested and certified to the Packing Group I performance level at a specific gravity of not less than 1.8.",
  N43: "Metal drums are permitted as single packaging's only if constructed of nickel or Monel.",
  N85: "Packagings certified at the Packing Group I performance level may not be used.",
  N86: "UN pressure receptacles made of aluminum alloy are not authorized.",
  N87: "The use of copper valves on UN pressure receptacles is prohibited.",
  N90: "Metal packagings are not authorized.",
};
