type CargoType = string;
type MayContain = string[];

/* Table A3.2. Hidden Hazardous Shipment Indicators */
const hiddenHazardIndicators: Record<CargoType, MayContain> = {
  "Aircraft and Aircraft Parts": [
    "batteries",
    "explosives",
    "chemical oxygen generators",
    "compressed gas cylinders (fire extinguishers)",
    "oxygen bottles",
    "fuel cells",
    "fuel devices",
    "radioactive material",
    "secondary loads",
    "survival kits",
  ],
  "Breathing Apparatus/SCUBA": [
    "compressed air",
    "compressed gasses including oxygen in cylinders",
  ],
  "Cleaning Supplies": ["solvents", "flammable liquids", "corrosive material"],
  "Containerized Loads": ["multiple hazards"],
  Cryogenics: ["liquid argon", "helium", "nitrogen", "oxygen"],
  Cylinders: ["compressed gas"],
  "Deployment Equipment": [
    "batteries",
    "flammable liquids",
    "gas",
    "solids",
    "fuel cells",
    "lithium batteries",
    "radioactive material",
  ],
  "Electrical Equipment": [
    "batteries",
    "lithium batteries",
    "magnetized materials",
    "mercury in switches or electron tubes",
    "radioactive material",
  ],
  "Frozen Foods": ["dry ice"],
  "Fuel Devices": ["residual fuel (especially if used or unserviceable)"],
  "Generators, Engines and Ground SE": [
    "batteries",
    "compressed gas cylinders (fire extinguishers)",
    "explosives",
    "fuel cells",
    "fuel devices",
  ],
  "Household Products": ["paint", "aerosols", "bleach", "radioactive material"],
  "Individual Equipment Items": [
    "aerosols",
    "batteries",
    "lithium batteries",
    "flammable gas",
    "radioactive materials",
  ],
  Instruments: [
    "batteries",
    "lithium batteries",
    "mercury",
    "radioactive materials",
  ],
  "Laboratory Samples": [
    "hazardous chemicals",
    "infectious substances",
    "radioactive material",
  ],
  "Machinery Parts": [
    "adhesives",
    "hazardous chemicals",
    "paints",
    "sealants",
    "solvents",
  ],
  "Medical Supplies/Equipment": [
    "batteries",
    "lithium batteries",
    "hazardous chemicals",
    "radioactive materials",
  ],
  "Pharmaceuticals, Vaccines": ["dry ice", "hazardous chemicals"],
  "Repair Kits": [
    "adhesives",
    "hazardous chemicals",
    "paints",
    "solvents",
    "organic peroxides",
  ],
  "Survival Kits": [
    "aerosols",
    "batteries",
    "compressed gas",
    "flammable solids",
    "lithium batteries",
  ],
  "Tool Boxes": [
    "adhesives",
    "cleaners",
    "compressed gas",
    "lubricants",
    "paints",
    "sealers",
    "solvents",
  ],
  "Uninterrupted Power Supply (UPS)": [
    "batteries",
    "lithium ion and metal batteries",
    "lead-acid nonspillable batteries",
  ],
  "Vehicles and Vehicle Parts": [
    "additional fuel",
    "air bag inflators/air bag modules",
    "batteries",
    "fire extinguishers",
    "fuel cells",
    "fuel devices",
    "paints",
    "radioactive material",
    "secondary loads",
    "shocks/struts with compressed gas",
  ],
  "Vessels and Vessel Parts": [
    "batteries",
    "compressed gas cylinders (fire extinguishers)",
    "SCUBA",
    "explosives",
    "flares",
    "fuel cells",
    "fuel devices",
    "life rafts",
    "secondary loads",
  ],
};
