import {
  hazardousMaterialsList,
  type HazardousMaterialItem,
} from "./hazardousMaterialsList";

// export const hazardousMaterialsA13List: HazardousMaterialItem[] =
//   hazardousMaterialsList.filter(material =>
//     material.packagingParagraph.startsWith("A13")
//   );

export const hazardousMaterialsA13List: HazardousMaterialItem[] = [
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN1841",
    "properShippingName": "ACETALDEHYDE AMMONIA",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.14."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2071",
    "properShippingName": "AMMONIUM NITRATE BASED FERTILIZER",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 132",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": true,
    "unid": "UN3548",
    "properShippingName": "ARTICLES CONTAINING MISCELLANEOUS DANGEROUS GOODS, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 391",
    "packagingParagraph": "A13.5"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": false,
    "unid": "NA2212",
    "properShippingName": "ASBESTOS",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 156",
    "packagingParagraph": "A13.16."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": true,
    "unid": "UN2212",
    "properShippingName": "ASBESTOS, AMPHIBOLE",
    "details": "amosite, tremolite, actinolite, anthopphylite, or crocidolite",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5, 156",
    "packagingParagraph": "A13.16."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2590",
    "properShippingName": "ASBESTOS, CHRYSOTILE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 156",
    "packagingParagraph": "A13.16."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": true,
    "unid": "UN3334",
    "properShippingName": "AVIATION REGULATED LIQUID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, A35, A506",
    "packagingParagraph": "A13.14."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": true,
    "unid": "UN3335",
    "properShippingName": "AVIATION REGULATED SOLID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, A35, A506",
    "packagingParagraph": "A13.14."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3171",
    "properShippingName": "BATTERY-POWERED EQUIPMENT",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 134",
    "packagingParagraph": "A13.6."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3171",
    "properShippingName": "BATTERY-POWERED VEHICLE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 134",
    "packagingParagraph": "A13.6."
  },
  {
    "isFixed": "true",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN1990",
    "properShippingName": "BENZALDEHYDE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3508",
    "properShippingName": "CAPACITOR, ASYMMETRIC",
    "details": "with an energy storage capacity greater than 0.3 Wh",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.19."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3499",
    "properShippingName": "CAPACITOR, ELECTRIC DOUBLE LAYER",
    "details": "with an energy storage capacity greater than 0.3 Wh",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.19."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN1845",
    "properShippingName": "CARBON DIOXIDE, SOLID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.10."
  },
  // {
  //   "isFixed": "false",
  //   "isDomesticShipment": false,
  //   "isTechnicalNameRequired": false,
  //   "unid": "UN1845",
  //   "properShippingName": "CARBON DIOXIDE, DRY ICE",
  //   "hazclassDiv": "9",
  //   "subsidiaryRisk": "",
  //   "packingGroup": "",
  //   "specialProvision": "P5",
  //   "packagingParagraph": "A13.10."
  // },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2969",
    "properShippingName": "CASTOR BEANS",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2969",
    "properShippingName": "CASTOR MEAL",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2969",
    "properShippingName": "CASTOR POMACE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2969",
    "properShippingName": "CASTOR FLAKE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3316",
    "properShippingName": "CHEMICAL KIT",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.18."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "ID8000",
    "properShippingName": "CONSUMER COMMODITY",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, A503",
    "packagingParagraph": "A13.3."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3363",
    "properShippingName": "DANGEROUS GOODS IN APPARATUS",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.13."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3363",
    "properShippingName": "DANGEROUS GOODS IN MACHINERY",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.13."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN1941",
    "properShippingName": "DIBROMODIFLUOROMETHANE, R12B2",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3530",
    "properShippingName": "ENGINE, INTERNAL COMBUSTION",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 135, A87",
    "packagingParagraph": "A13.20"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3530",
    "properShippingName": "MACHINERY, INTERNAL COMBUSTION",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 135, A87",
    "packagingParagraph": "A13.20"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": true,
    "unid": "UN3082",
    "properShippingName": "ENVIRONMENTALLY HAZARDOUS SUBSTANCE, LIQUID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 8, A197",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": true,
    "unid": "UN3077",
    "properShippingName": "ENVIRONMENTALLY HAZARDOUS SUBSTANCE, SOLID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 8, A197",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3316",
    "properShippingName": "FIRST AID KIT",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.18."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2216",
    "properShippingName": "FISH MEAL, STABILIZED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 155",
    "packagingParagraph": "A13.2"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2216",
    "properShippingName": "FISH SCRAP, STABILIZED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, 155",
    "packagingParagraph": "A13.2"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": true,
    "unid": "NA3082",
    "properShippingName": "HAZARDOUS WASTE, LIQUID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": true,
    "unid": "NA3077",
    "properShippingName": "HAZARDOUS WASTE, SOLID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3072",
    "properShippingName": "LIFE-SAVING APPLIANCES, NOT SELF INFLATING",
    "details": "containing dangerous goods as equipment",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 182",
    "packagingParagraph": "A13.12."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2990",
    "properShippingName": "LIFE-SAVING APPLIANCES, SELF INFLATING",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.12."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3536",
    "properShippingName": "LITHIUM BATTERIES INSTALLED IN A CARGO TRANSPORT UNIT",
    "details": "lithium ion batteries or lithium metal batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 389",
    "packagingParagraph": "A13.8"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3480",
    "properShippingName": "LITHIUM ION BATTERIES",
    "details": "including lithium polymer batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 388",
    "packagingParagraph": "A13.7."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3481",
    "properShippingName": "LITHIUM ION BATTERIES CONTAINED IN EQUIPMENT",
    "details": "including lithium polymer batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 388",
    "packagingParagraph": "A13.8."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3481",
    "properShippingName": "LITHIUM ION BATTERIES PACKED WITH EQUIPMENT",
    "details": "including lithium polymer batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 388",
    "packagingParagraph": "A13.9."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3090",
    "properShippingName": "LITHIUM METAL BATTERIES",
    "details": "including lithium alloy batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P4, 388",
    "packagingParagraph": "A13.7."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3091",
    "properShippingName": "LITHIUM METAL BATTERIES CONTAINED IN EQUIPMENT",
    "details": "including lithium alloy batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P4, 388",
    "packagingParagraph": "A13.8."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3091",
    "properShippingName": "LITHIUM METAL BATTERIES PACKED WITH EQUIPMENT",
    "details": "including lithium alloy batteries",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P4, 388",
    "packagingParagraph": "A13.9"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2807",
    "properShippingName": "MAGNETIZED MATERIAL",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5",
    "packagingParagraph": "A13.11."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": false,
    "unid": "NA3082",
    "properShippingName": "OTHER REGULATED SUBSTANCES, LIQUID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": false,
    "unid": "NA3077",
    "properShippingName": "OTHER REGULATED SUBSTANCES, SOLID, N.O.S.",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3314",
    "properShippingName": "PLASTIC MOULDING COMPOUND",
    "details": "in dough, sheet, or extruded rope form evolving flammable vapor",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.17."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2315",
    "properShippingName": "POLYCHLORINATED BIPHENYLS, LIQUID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5, 9",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3432",
    "properShippingName": "POLYCHLORINATED BIPHENYLS, SOLID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5, 9",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3151",
    "properShippingName": "POLYHALOGENATED BIPHENYLS, LIQUID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3151",
    "properShippingName": "HALOGENATED MONOMETHYLDIPHENYLMETHANES, LIQUID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3151",
    "properShippingName": "POLYHALOGENATED TERPHENYLS, LIQUID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3152",
    "properShippingName": "POLYHALOGENATED BIPHENYLS, SOLID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3152",
    "properShippingName": "HALOGENATED MONOMETHYLDIPHENYLMETHANES, SOLID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3152",
    "properShippingName": "POLYHALOGENATED TERPHENYLS, SOLID",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "II",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2211",
    "properShippingName": "POLYMERIC BEADS, EXPANDABLE",
    "details": "evolving flammable vapor",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.17."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3268",
    "properShippingName": "SAFETY DEVICES",
    "details": "electrically initiated",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 160",
    "packagingParagraph": "A13.15."
  },
  {
    "isFixed": "true",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": false,
    "unid": "NA3334",
    "properShippingName": "SELF-DEFENSE SPRAY, NON-PRESSURIZED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5, A37",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": true,
    "isTechnicalNameRequired": false,
    "unid": "NA1350",
    "properShippingName": "SULFUR",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3166",
    "properShippingName": "VEHICLE, FLAMMABLE GAS POWERED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 135",
    "packagingParagraph": "A13.4."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3166",
    "properShippingName": "VEHICLE, FUEL CELL, FLAMMABLE GAS POWERED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 135",
    "packagingParagraph": "A13.4."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3166",
    "properShippingName": "VEHICLE, FLAMMABLE LIQUID POWERED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 135",
    "packagingParagraph": "A13.4."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN3166",
    "properShippingName": "VEHICLE, FUEL CELL, FLAMMABLE LIQUID POWERED",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "",
    "specialProvision": "P5, 135",
    "packagingParagraph": "A13.4."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN2590",
    "properShippingName": "WHITE ASBESTOS",
    "details": "anthophyllite",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.16"
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN1931",
    "properShippingName": "ZINC DITHIONITE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  },
  {
    "isFixed": "false",
    "isDomesticShipment": false,
    "isTechnicalNameRequired": false,
    "unid": "UN1931",
    "properShippingName": "ZINC HYDROSULFITE",
    "hazclassDiv": "9",
    "subsidiaryRisk": "",
    "packingGroup": "III",
    "specialProvision": "P5",
    "packagingParagraph": "A13.2."
  }
]
